name: Build

on:
  push:
    branches:
      - dev
      - master
    tags:
      - v**

jobs:
  build:
    name: Build ${{ matrix.ver }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - mipsel_24kc
          - x86_64
        ver:
          - '24.10'
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Building packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-openwrt-${{ matrix.ver }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-shadowsocks-libev shadowsocks-libev
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.ver }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Upload packages
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
